POST http://localhost:8080/api/uaa/signin
Content-Type: application/json

{
  "username": "admin@miu.edu",
  "password": "admin"
}

###

GET http://localhost:8080/api/data/batch
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBtaXUuZWR1IiwiaWF0IjoxNjYyNTc2MDk0LCJleHAiOjE2NjI1ODE0OTR9.P70v9eTWqEJjJ2YxwLqsjqdSFtEcTtnutbSi3BucDYXMVhpKVOTBFz5HdRs4nbU5kEG-bcWkry0x7daOAs5fKA
###
